### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::unionPaginate()

### ISSUE THREAD

**Issue by akhileshdarjee** [krossroad/laravel-unionpaginator#1]
I'm using following stack: 

- Laravel 5.5.28
- PHP 7.0.25
- MySQL 5.7.18

I've tried using Query Builder and Model, none of them worked. Please help :)

**Comment by krossroad** [comment]
Did you use `UnionPaginatorTrait` in your model?

**Comment by akhileshdarjee** [comment]
Yes. Here is my code:

`<?php

namespace App\Http\Controllers;

use DB;
use App\Activity;
use Krossroad\UnionPaginator\UnionPaginatorTrait;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ActivityController extends Controller
{
    use UnionPaginatorTrait;

    public function show(Request $request)
    {
        $fetch_fields = [
            'id', 'user_id', 'user', 'module', 'icon', 'action', 
            'form_id', 'form_title'
        ];

        $activities = Activity::whereNotNull('id');

        if (auth()->user()->role != 'System Administrator') {
            $module_ids_map = [
                'User' => [20, 25, 66, 32],
                'Client' => [1, 5, 77, 34, 63, 29]
            ];

            if ($module_ids_map && count($module_ids_map)) {
                foreach ($module_ids_map as $module => $ids) {
                    if ($ids && count($ids)) {
                        $conditions = Activity::where('module', $module)
                            ->whereIn("form_id", $ids);

                        $activities = $activities->union($conditions);
                    }
                }
            }
        }

        $activities = $activities->orderBy('created_at', 'desc')
            ->unionPaginate(20, $fetch_fields, $pageName = 'page', $request->get('page'));

        $current_user = auth()->user();
        return response()->json(compact('activities', 'current_user'), 200);
    }
}
`

Can you tell me, what's wrong here?

**Comment by akhileshdarjee** [comment]
I've used the code in Controller & not in Model.
I hope it supports the code on Controller also?

**Comment by krossroad** [comment]
You’re supposed to use that trait in your model not in your controller.

**Comment by akhileshdarjee** [comment]
Okk, I've used the `UnionPaginatorTrait` in my 'Activity' Model.
`unionPaginate()` method is working :)
