### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by stephweb** [krossroad/laravel-unionpaginator#15]
Hello.

Please:
Can we have your package compatible with laravel 6 ?

Thank you so much.

**Comment by krossroad** [comment]
@stephweb, Sorry for the late reply. As for porting this package to **laravel 6**, there is no need as from **laravel 5.7** there is support for pagination in union-queries in laravel's query builder itself. 
Checkout **laravel/framework#26466**.
Cheers.

**Comment by krossroad** [comment]
Closing this issue for now

**Comment by s-damian** [comment]
Hello.

I tested pagination in union-queries with a Laravel 5.8 project, it doesn't work.
I like your package.
Can you update it for Laravcel 6 please?

Thank you.
